site_name: Manuale utente 1.0.0 | Stalker
repo_url: https://github.com/qb-team/Stalker-ManualeUtente

theme:
  name: material
  custom_dir: "docs_theme"

markdown_extensions:
  # https://github.com/g-provost/lightgallery-markdown
  - lightgallery
  # https://squidfunk.github.io/mkdocs-material/extensions/admonition/
  - admonition
  # https://squidfunk.github.io/mkdocs-material/extensions/codehilite/
  - codehilite

nav:
  - Il gruppo qbteam: "qbteam.md"
  - Registro modifiche: "registromodifiche.md"
  - 1 Introduzione: "index.md"
  - 2 App utenti:
      - 2.1 Funzionalità: "app/funzionalita.md"
  - 3 Web-app amministratori:
      - 3.1 Funzionalità: "webapp/funzionalita.md"
  - A Glossario: "glossario.md"
