site_name: Manuale sviluppatore | Stalker
repo_url: https://github.com/qb-team/Stalker-Documentazione/

theme:
  name: material
  custom_dir: "docs_theme"

markdown_extensions:
  - lightgallery
  - admonition

nav:
  - Home: "index.md"
  - Registro modifiche: "registromodifiche.md"
  - App utenti:
      - Introduzione: "app/introduzione.md"
      - Requisiti e installazione: "app/requisiti.md"
      - Estendibilità: "app/estendibilita.md"
      - Architettura: "app/architettura.md"
      - Package: "app/package.md"
      - Diagrammi delle classi: "app/classi.md"
      - Diagrammi di sequenza: "app/sequenza.md"
  - Web-app amministratori:
      - Introduzione: "webapp/introduzione.md"
      - Requisiti e installazione: "webapp/requisiti.md"
      - Estendibilità: "webapp/estendibilita.md"
      - Architettura: "webapp/architettura.md"
      - Package: "webapp/package.md"
      - Diagrammi delle classi: "webapp/classi.md"
      - Diagrammi di sequenza: "webapp/sequenza.md"
  - Backend:
      - Introduzione: "backend/introduzione.md"
      - Requisiti e installazione: "backend/requisiti.md"
      - Estendibilità: "backend/estendibilita.md"
      - Architettura: "backend/architettura.md"
      - Package: "backend/package.md"
      - Diagrammi delle classi: "backend/classi.md"
      - Diagrammi di sequenza: "backend/sequenza.md"
  - REST API:
      - Introduzione: "restapi/introduzione.md"
      - Specifica OpenAPI e Swagger: "restapi/openapi.md"
      - Utilizzo: "restapi/utilizzo.md"
      - Documentazione: "restapi/documentazione.md"
      - Modello:
        - AdministratorBindingRequest: "restapi/model/AdministratorBindingRequest.md"
        - Favorite: "restapi/model/Favorite.md"
        - OrganizationAccess: "restapi/model/OrganizationAccess.md"
        - Organization: "restapi/model/Organization.md"
        - OrganizationMovement: "restapi/model/OrganizationMovement.md"
        - OrganizationPresenceCounter: "restapi/model/OrganizationPresenceCounter.md"
        - Permission: "restapi/model/Permission.md"
        - PlaceAccess: "restapi/model/PlaceAccess.md"
        - Place: "restapi/model/Place.md"
        - PlaceMovement: "restapi/model/PlaceMovement.md"
        - PlacePresenceCounter: "restapi/model/PlacePresenceCounter.md"
        - TimePerUserReport: "restapi/model/TimePerUserReport.md"
      - Api:
        - AccessApi: "restapi/api/AccessApi.md"
        - AdministratorApi: "restapi/api/AdministratorApi.md"
        - FavoriteApi: "restapi/api/FavoriteApi.md"
        - MovementApi: "restapi/api/MovementApi.md"
        - OrganizationApi: "restapi/api/OrganizationApi.md"
        - PlaceApi: "restapi/api/PlaceApi.md"
        - PresenceApi: "restapi/api/PresenceApi.md"
        - ReportApi: "restapi/api/ReportApi.md"